# Site settings
title: Clair de lune 
url: "https://koremp.github.io"
baseurl: ""
description: >
  Claude Debussy - Clair de lune

# My information
email: im.koremp@gmail.com
author: 클레어, Claire
profile: 복잡한 사람
twitter_username: cad__claireh
github_username: koremp
# comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: koremp/koremp.github.io
  repo_id: SAMPLE-VALUE
  category: Announcements
  category_id: SAMPLE-VALUE

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/koremp/koremp.github.io/blame/main/_wiki"
edit: "https://github.com/koremp/koremp.github.io/edit/main/_wiki"
issue: "https://github.com/koremp/koremp.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
